module.exports = {
    getCeramicName: function() {
        var ceramic_name = ['Geoslate',
        'Eterna Coffee',
        'Eterna Cotto',
        'Eterna Crema',
        'Eterna Viola',
        'Eterna Gris',
        'Eterna Pearl',
        'Starlet Coral',
        'Mandala Pink Crush',
        'Mandala Desert Palm',
        'Mandala Bianco',
        'Fusion Swatch',
        'Galactic Mist',
        'Galactic Copper',
        'Galactic Cloud Blue',
        'Vermont Horizon',
        'Parco Rosso',
        'Parco Verde',
        'Parco Gris',
        'Parco Viola',
        'Parker Taupe',
        'Castano Honey',
        'Austin Brown',
        'Unico Crema',
        'Incredic Nero',
        'Armani Crema',
        'Mistero Verde',
        'Elmas Gris',
        'Rare Greek Vase & Decor',
        'Rare Steel Blue',
        'Rare Nimbus Shower',
        'Rare Eclipse',
        'Rare Turtle Shell',
        'Rare Antique Brass',
        'Rare Sunset Cloud',
        'Sapphire Ice Age',
        'Parker Nero',
        'Parker Gris',
        'Parker Bianco',
        'Parker Crema',
        'Woodland Verde',
        'Oakland Ochre',
        'Grenier Gris',
        'Ethos Pearl',
        'Travertino Natural',
        'Imperia Choco',
        'Elite Crema',
        'Desert Crema',
        'Tepic Silver',
        'Spiderweb Crema',
        'Turin Beige',
        'Prisma Gris',
        'Oceanic Bianco',
        'Miami Beige',
        'Aspire Bianco',
        'Grorious Beige',
        'Olbia Beige',
        'Linz Crema',
        'Iceland',
        'Statuario Vogue',
        ]
        return ceramic_name;
    },

    getCeramicLink: function(){
        var ceramic_link = ['geoslate.jpg',
        'eterna-coffee.jpg',
        'eterna-cotto.jpg',
        'eterna-crema.jpg',
        'eterna-viola.jpg',
        'eterna-gris.jpg',
        'eterna-pearl.jpg',
        'starlet-coral.jpg',
        'mandala-pink-crush.jpg',
        'mandala-desert-palm.jpg',
        'mandala-bianco.jpg',
        'fusion-swatch.jpg',
        'galactic-mist.jpg',
        'galactic-copper.jpg',
        'galactic-cloud-blue.jpg',
        'vermont-horizon.jpg',
        'parco-rosso.jpg',
        'parco-verde.jpg',
        'parco-gris.jpg',
        'parco-viola.jpg',
        'parker-taupe.jpg',
        'castano-honey.jpg',
        'austin-brown.jpg',
        'unico-crema.jpg',
        'incredic-nero.jpg',
        'armani-crema.jpg',
        'mistero-verde.jpg',
        'elmas-gris.jpg',
        'rare-greek-vase.jpg',
        'rare-steel-blue.jpg',
        'rare-nimbus-shower.jpg',
        'rare-eclipse.jpg',
        'rare-turtle-shell.jpg',
        'rare-antique-brass.jpg',
        'rare-sunset-cloud.jpg',
        'sapphire-ice-age.jpg',
        'parker-nero.jpg',
        'parker-gris.jpg',
        'parker-bianco.jpg',
        'parker-crema.jpg',
        'woodland-verde.jpg',
        'oakland-ochre.jpg',
        'grenier-gris.jpg',
        'ethos-pearl.jpg',
        'travertino-natural.jpg',
        'imperia-choco.jpg',
        'elite-crema.jpg',
        'desert-crema.jpg',
        'tepic-silver.jpg',
        'spiderweb-crema.jpg',
        'turin-beige.jpg',
        'prisma-gris.jpg',
        'oceanic-bianco.jpg',
        'miami-beige.jpg',
        'aspire-bianco.jpg',
        'grorious-beige.jpg',
        'olbia-beige.jpg',
        'linz-crema.jpg',
        'iceland.jpg',
        'statuario-vogue.jpg',
        ]

        return ceramic_link;
    }
}










