module.exports = {
    getCeramicName: function() {
        var ceramic_name = ['Wozti Nut',
        'Aristo Rosso',
        'Monolith Deep Dig',
        'Statuario Magma',
        'Marca Indigo',
        'Marca Scarlet',
        'Marca Caramel',
        'Marca Coal',
        'Monolith Stone Age',
        'Monolith Creamy Crust',
        'Lilac Purple',
        'Hordix Pearl',
        'Hordix Camel',
        'Hordix Gris',
        'Hordix Silver',
        'Saran Collin Gris',
        'Saran Collin Camel',
        'Calcatta Gold',
        'Onyx Verde',
        'Onyx Sunspot',
        'Onyx Sea Blue',
        'Onyx Pink Crush',
        'Travertino Beige',
        'Rapido Gris',
        'Rapido Crema',
        'Mirage Gris',
        'Stellar Nero',
        'Lithics Nero',
        'Nero Marquina',
        'Forever Nero',
        'Forever Hote Spring',
        'Prestige Choco',
        'Armani Gris',
        'Nobel',
        'Riseonic',
        'Dyno Crema',
        'Stonella Gris',
        'Stonella Crema',
        'Stonella Dull Brich',
        'Stonella Ice Crystal',
        'Stonella Dark Shadow',
        'Stonella Steel Grey',
        'Thar Wood',
        'Thar Dawn',
        'Thar Sand',
        'Thar Coal',
        'Thar Smoke',
        'Statuario Bauxite',
        'Ethnic Custard Apple',
        'Ethnic Jet Stream',
        'Elmas Nero',
        'Elmas Rosata',
        'Zenith',
        'Thunder Cream Pie',
        'Lait Travertino',
        'Crowdux Bianco',
        'Crowdux Crema',
        'Bondford Viola',
        'Bondford Silver',
        'Bondford Ivory',
        'Purecure Pearl',
        'Daxon Wine',
        'Legend Silver',
        'Lambert Gold',
        'Cosmos Gold',
        'Blue Pearl',
        'Trixxon Blue',
        'Mistero Nero',
        'Marvel Gris',
        'Harmony Gris',
        'Harmony Beige',
        'Botticino',
        'Armani Crema',
        'Statuario Mercury',
        'Rosalia',
        'Castano Gris',
        'Oceanic Bianco',
        'Oceanic Crema',
        'Soul Crema',
        'Belmont Pearl',
        'Tepic Crema',
        'Unico Coffee',
        'Incredic Crema',
        'Latin Beige',
        'Perlato Pearl',
        'Paradise Silver',
        'Fossil Crema',
        'Downtown Choco',
        'Berlin Beige',
        'Breccia Crema',
        'Artistic Almond',
        'Onyx Gris',
        'Onyx Pearl',
        'Miami Beige',
        'Iceland',
        'Statuario Pluto',
        ]
        return ceramic_name;
    },

    getCeramicLink: function(){
        var ceramic_link = ['wozti-nut.jpg',
        'aristo-rosso.jpg',
        'monolith-deep-dig.jpg',
        'statuario-magma.jpg',
        'marca-indigo.jpg',
        'marca-scarlet.jpg',
        'marca-caramel.jpg',
        'marca-coal.jpg',
        'monolith-stone-age.jpg',
        'monolith-creamy-crust.jpg',
        'lilac-purple.jpg',
        'hordix-pearl.jpg',
        'HORDIX-CAMEL.jpg',
        'hordix-gris.jpg',
        'hordix-silver.jpg',
        'saran-collin-gris.jpg',
        'saran-collin-camel.jpg',
        'calcatta-gold.jpg',
        'onyx-verde.jpg',
        'onyx-sunspot.jpg',
        'onyx-sea-blue.jpg',
        'onyx-pink-crush.jpg',
        'travertino-beige.jpg',
        'rapido-gris.jpg',
        'rapido-crema.jpg',
        'mirage-gris.jpg',
        'stellar-nero.jpg',
        'lithics-nero.jpg',
        'nero-marquina.jpg',
        'forever-nero.jpg',
        'forever-hote-spring.jpg',
        'prestige-choco.jpg',
        'armani-gris.jpg',
        'nobel.jpg',
        'riseonic.jpg',
        'dyno-crema.jpg',
        'stonella-gris.jpg',
        'stonella-crema.jpg',
        'stonella-dull-brich.jpg',
        'stonella-ice-crystal.jpg',
        'stonella-dark-shadow.jpg',
        'stonella-steel-grey.jpg',
        'thar-wood.jpg',
        'thar-dawn.jpg',
        'thar-sand.jpg',
        'thar-coal.jpg',
        'thar-smoke.jpg',
        'statuario-bauxite.jpg',
        'ethnic-custard-apple.jpg',
        'ethnic-jet-stream.jpg',
        'elmas-nero.jpg',
        'elmas-rosata.jpg',
        'zenith.jpg',
        'thunder-cream-pie.jpg',
        'lait-travertino.jpg',
        'crowdux-bianco.jpg',
        'crowdux-crema.jpg',
        'bondford-viola.jpg',
        'bondford-silver.jpg',
        'bondford-ivory.jpg',
        'purecure-pearl.jpg',
        'daxon-wine.jpg',
        'legend-silver.jpg',
        'lambert-gold.jpg',
        'cosmos-gold.jpg',
        'blue-pearl.jpg',
        'trixxon-blue.jpg',
        'mistero-nero.jpg',
        'marvel-gris.jpg',
        'harmony-gris.jpg',
        'harmony-beige.jpg',
        'botticino.jpg',
        'armani-crema.jpg',
        'statuario-mercury.jpg',
        'rosalia.jpg',
        'castano-gris.jpg',
        'oceanic-bianco.jpg',
        'oceanic-crema.jpg',
        'soul-crema.jpg',
        'BELMONT-PEARL.jpg',
        'tepic-crema.jpg',
        'unico-coffee.jpg',
        'incredic-crema.jpg',
        'latin-beige.jpg',
        'perlato-pearl.jpg',
        'paradise-silver.jpg',
        'fossil-crema.jpg',
        'downtown-choco.jpg',
        'berlin-beige.jpg',
        'breccia-crema.jpg',
        'artistic-almond.jpg',
        'onyx-gris.jpg',
        'onyx-pearl.jpg',
        'miami-beige.jpg',
        'iceland.jpg',
        'statuario-pluto.jpg']

        return ceramic_link;
    }
}










