module.exports = {
    getGraniteName: function() {
        var granite_name = ['Alaska Red Granite',
        'Wine Red Granite',
        'Ivory Chiffon Granite',
        'Cats Eye Granite',
        'River Gold Granite',
        'Black Marcino Granite',
        'Zebra Black Granite',
        'Cappuccino White',
        'Koliwada Blue Granite',
        'Green Pearl Granite',
        'Alaska Gold Granite',
        'Tropical Blue',
        'Monte Cristo',
        'Imperial Blue',
        'Nosera French Green',
        'Surf Green Granite',
        'Tiger Skin Granite',
        'Sparkle Brown Granite',
        'Titanium White Granite',
        'Thunder White Granite',
        'Strawberry Pink Granite',
        'Smoka Red Granite',
        'Sea Wave Granite',
        'Nova Black Granite',
        'Millenium Cream',
        'Jubilee Grey',
        'Ivory Fantasy Granite',
        'Indian Aurora Granite',
        'Imperial Gold Granite',
        'Golden Trauma Granite',
        'Golden Beach Granite',
        'French White Granite',
        'Flash Blue Granite',
        'Colonial White Granite',
        'Colonial Cream Granite',
        'Blue Dunes Granite',
        'Black Premium Granite',
        'Binaco Gold Granite',
        'Astoria Pink Granite',
        'Astoria Gold Granite',
        'Astoria Granite',
        'Bhama Ivory Granite',
        'Black Marquina Granite',
        'S White Granite',
        'Royal Cream Granite',
        'Malwada Yellow Granite',
        'Kotkasta Granite',
        'Alaska White',
        'Ivory Gold Granite',
        'Parada Gold Granite',
        'Jet Black Granite',
        'Kuppam Green Granites',
        'Impala Black Granite',
        'Ghiblee Pink Granite',
        'Classic Paradiso Granite',
        'Black Marine 340X192X2Cm Slabs',
        'Black Forest Granite',
        'Z Brown Granite',
        'Topaz Blue Granite',
        'Rue Classic Granite',
        'Rue Black Granite',
        'Royal Green Granite',
        'Rosy Pink Granite',
        'P White Granite',
        'Onida Orange Granite',
        'New Imperial Red Granite',
        'Merry Gold Granite',
        'Lakha Red',
        'Jhansi Red Granite',
        'Desert Green Granite',
        'Desert Gold',
        'Desert Brown Granite',
        'Crystal Yellow Granite',
        'Copper Silk Granite',
        'Chima Pink',
        'Black Beauty Granite',
        'Baltic Brown',
        'Bala Flower Granite',
        'Viscon White',
        'Tan Brown Granite',
        'Steel Grey Granite',
        'Rose Wood Granite',
        'River White Granite',
        'Red Multicolor Granite',
        'Moon White Granite',
        'Lemon Ice Granite',
        'Lavender Blue Granite',
        'New Kashmir White Granite',
        'Absolute Black Granite',
        'Ivory Chiffon Granite',
        'Ivory Brown Granite',
        'Inkas Gold Granite',
        'Imperial White Granite',
        'Imperial Pink',
        'Himalayan Blue',
        'Hassan Green Granite',
        'Giblee Granite',
        'English Teak Granite',
        'Colonial Gold Granite',
        'Colombo Juprana Granitese',
        ]
        return granite_name;
    },

    getGraniteLink: function(){
        var granite_link = ['Alaska-red-granite--260x260.jpg',
        'Wine-red-granite-260x260.png',
        'ivory-chiffon-granite-260x260.jpg',
        'Cats-eye-granite-260x260.jpg',
        'River-Gold-Granite-260x260.jpg',
        'Black-Marcino-Granite-1-260x260.jpg',
        'Zebra-Black-Granite-260x260.jpg',
        'Cappuccino-White-260x260.jpg',
        'Koliwada-Blue-Granite-260x260.jpg',
        'Green-Pearl-Granite-260x260.jpg',
        'Alaska-Gold-Granite-260x260.jpg',
        'Tropical-Blue-260x260.jpg',
        'Monte-Cristo-260x260.jpg',
        'Imperial-Blue-260x260.jpg',
        'Nosera-French-Green-260x260.jpg',
        'Surf-Green-Granite-260x260.jpg',
        'Tiger-Skin-Granite-260x260.jpg',
        'Sparkle-Brown-260x260.jpg',
        'Titanium-White-Granite-260x260.jpg',
        'Thunder-White-Granite-260x260.jpg',
        'Strawberry-Pink-Granite-260x260.jpg',
        'Smoka-Red-260x260.jpg',
        'Sea-Wave-260x260.jpg',
        'Nova-Black-260x260.jpg',
        'Millenium-Cream-260x260.jpg',
        'Jubilee-Grey-260x260.jpg',
        'Ivory-Fantasy-260x260.jpg',
        'Indian-Aurora-Granite-260x260.jpg',
        'Imperial-Gold-Granite-260x260.jpg',
        'Golden-Trauma-260x260.jpg',
        'Golden-Beach-Granite-260x260.jpg',
        'French-White-Granite-260x260.jpg',
        'Flash-Blue-260x260.jpg',
        'Colonial-White-Granite-260x260.jpg',
        'Colonial-Cream-260x260.jpg',
        'Blue-Dunes-260x260.jpg',
        'Black-Premium-260x260.jpg',
        'Binaco-Gold-260x260.jpg',
        'Astoria-Pink-260x260.jpg',
        'Astoria-Gold-Granite-260x260.jpg',
        'Astoria-260x260.jpg',
        'Bhama-ivory-granite-260x260.jpg',
        'Black-Marquina-Granite-260x260.jpg',
        'S-White-Granite-260x260.jpg',
        'Royal-Cream-260x260.jpg',
        'Malwada-Yellow-Granite-260x260.jpg',
        'Kotkasta-Granite-Doneh-1-260x260.jpg',
        'Alaska-White-260x260.jpg',
        'Ivory-Gold-Granite-260x260.jpg',
        'Parada-Gold-260x260.jpg',
        'Jet-Black-260x260.jpg',
        'Kuppam-Green-Granites-260x260.jpg',
        'Impala-Black-Granite-260x260.jpg',
        'Ghiblee-Pink-260x260.jpg',
        'Classic-Paradiso-Granite-260x260.jpg',
        'Black-Marine-BL.-No.-440-340x192-2cm-10-SlabsClose-Up-1-260x260.jpg',
        'Black-Forest-Granite-260x260.jpg',
        'Z-Brown-Granite-260x260.jpg',
        'Topaz-Blue-Granite-260x260.jpg',
        'Rue-Classic-Granite-260x260.jpg',
        'Rue-Black-Granite-260x260.jpg',
        'Royal-Green-Granite-260x260.jpg',
        'Rosy-Pink-Granite-260x260.jpg',
        'P-White-Granite-260x260.jpg',
        'main-1-260x260.jpg',
        'New-Imperial-Red-Granite-260x260.jpg',
        'Merry-Gold-Granite-260x260.jpg',
        'Lekha-Red-260x260.jpg',
        'Jhansi-Red-Granite-260x260.jpg',
        'Desert-Green-260x260.jpg',
        'Desert-Gold-260x260.jpg',
        'Desert-Brown-Granite-260x260.jpg',
        'Crystal-Yellow-Granite-260x260.jpg',
        'Copper-Silk-Granite-260x260.jpg',
        'Chima-Pink--260x260.jpg',
        'Black-Beauty-260x260.jpg',
        'Baltic-Brown-260x260.jpg',
        'Bala-Flower-Granite-260x260.jpg',
        'Viscon-White1-260x260.jpg',
        'Tan-Brown-Granite-260x260.jpg',
        'Steel-Grey-Granite-260x260.jpg',
        'Rose-Wood-2-260x260.jpg',
        'River-White-Granite-260x260.jpg',
        'Red-Multicolor-Granite-260x260.jpg',
        'Moon-White-Granite-260x260.jpg',
        'Lemon-Ice-260x260.jpg',
        'Lavender-Blue-Granite-260x260.jpg',
        'New-Kashmir-White-Granite-260x260.jpg',
        'Absolute-Black-Granite-260x260.jpg',
        'Ivory-Ciffon-260x260.jpg',
        'Ivory-Brown-Granite-260x260.jpg',
        'Inkas-Gold-Granite-260x260.jpg',
        'Imperial-White-Granite-2-260x260.jpg',
        'Imperial-Pink-260x260.jpg',
        'Himalayan-Blue-260x260.jpg',
        'Hassan-Green-Granite-260x260.jpg',
        'Giblee-260x260.jpg',
        'English-Teak-260x260.jpg',
        'Colonial-Gold-260x260.jpg',
        'Colombo-Juprana-1-260x260.jpg',
        ]

        return granite_link;
    }
}










