module.exports = {
    getMarbleName: function() {
        var marble_name = ['Acupullo Brown',
        'Alaska Grey',
        'Alaska Grey Light Premium',
        'Alpin',
        'Amarone',
        'Amazon',
        'American Grey',
        'Antigua Brown',
        'Antique Beige',
        'Aragonite',
        'Armani Beige',
        'Armani Grey',
        'Ash Grey',
        'Astrus',
        'Astrus Grey  Variation 2',
        'Astrus Grey Variation 1',
        'Aura',
        'Avocatus',
        'Avorio',
        'Azul Macaubas Variation 1',
        'Azul Macaubas Variation 2',
        'Beige Serpeggiante',
        'Beige Travertine',
        'Belgium Black',
        'Bellatrix',
        'Belvedere',
        'Bethany Blue',
        'Beverely Blue',
        'Bianco Fusion',
        'Bianco Oro',
        'Bianco Oro Extra Classico',
        'Bianco Romano Classico',
        'Biancone',
        'Black &amp; Gold Daytona',
        'Black Fusion',
        'Black Horse',
        'Black Ice Pearl',
        'Black Marinace',
        'Black Shadow',
        'Black Swan',
        'Black Valley',
        'Blanc Luminix',
        'Blue Bahia',
        'Blue Flamingo',
        'Blue Fusion',
        'Blue Onyx',
        'Blue Onyx',
        'Blue Onyx',
        'Blue St. Tropez',
        'Borgini Gold',
        'Botanic Green',
        'Botticino Classico',
        'Botticino Crema',
        'Bottinica Gold Onyx',
        'Brasil Bronzetto',
        'Breche Bluette',
        'Brescia Aurora',
        'Brescia Blue',
        'Brescia Estrella',
        'Brescia Medicea',
        'Brescia Oniciata',
        'Bronze Amani',
        'Bronze Star',
        'Brown Antico',
        'Brown Earth',
        'Brown Malibu',
        'Bruno Perla',
        'Bulgari Grey',
        'Cafe Amaro',
        'Calacata Quartz',
        'Calacatta Vagli',
        'California Golden Grey',
        'Carpe Diem',
        'Cheyene',
        'Circuit Grey',
        'Classic Beige',
        'Classic Wave',
        'Claudia Crema Gold - Variation 2',
        'Claudia Crema Gold- Variation 1',
        'Cleopatra',
        'Colonial Blue',
        'Copa Cabana',
        'Coral Reef',
        'Cosmopolitian',
        'Crema Atlantica',
        'Crema Delicatus Onyx',
        'Crema Lumos',
        'Crema Valencia',
        'Crema Versailles Onyx',
        'Cristallo',
        'Cristallo Striato Onyx',
        'Dark Emperador',
        'Delicatus Mint',
        'Delux',
        'Desert Eagle',
        'Devci Grey',
        'Diana Venato',
        'Dijon Blue',
        'Duetto',
        'Emerald Quartzite',
        'Equilibrium',
        'Esparada',
        'Exuberant Brown',
        'Fascination',
        'Fascination Crystal',
        'Fenix Gold',
        'Fior De Pesco',
        'Fiora Grey',
        'Flamingo',
        'Fontaine',
        'Foresta',
        'Fossena',
        'Fossil Element',
        'French Chiffon',
        'Fusion',
        'Fusion Mint',
        'Gabana',
        'Gaya',
        'Giallo Siena',
        'Glacial Perla',
        'Golden Blue',
        'Golden Caramel',
        'Golden Dream',
        'Golden Emperador',
        'Golden Fenix',
        'Golden Flame',
        'Golden Fusion',
        'Golden Portoro',
        'Golden Spider',
        'Greek Chainti',
        'Greek Grey',
        'Greek Rosa Travertine',
        'Grey Corte',
        'Grey Dragon',
        'Grey Dusk',
        'Grey Flury',
        'Grey Frappuccino',
        'Grey Rio',
        'Grey Riviera',
        'Grey Santorini',
        'Grey Silver Travertine',
        'Grey Sonata',
        'Grey Sparkle',
        'Grey William',
        'Grey William Italy',
        'Grigio Amani',
        'Grigio Arizona',
        'Grigio Carnico',
        'Grigio Carpazi',
        'Grigio Celina',
        'Grigio Cielo',
        'Grigio Coralito',
        'Grigio D\'istria',
        'Grigio Esmeralda',
        'Grigio Espanol',
        'Grigio Orobico',
        'Hollywood Red',
        'Honey Lime Onyx',
        'Horizon',
        'Ice Berg Blue',
        'Ice Berg Onyx',
        'Ice Blue',
        'Ice Onyx',
        'Ijen Blue Variation 1',
        'Ijen Blue Variation 2',
        'Illusion',
        'Illusion Bronze',
        'Infinity Gold',
        'Invictus',
        'Italia Blue Onyx',
        'Italia Grey',
        'Jade Green Onyx',
        'Keylin Onyx',
        'Kozmus',
        'La Fabula',
        'Labradorite',
        'Light Emperador Golden',
        'London Grey Variation 1',
        'London Grey Variation 2',
        'Luise Cielo',
        'Lumix',
        'Luxuria',
        'Magma Gold',
        'Magma Gold Travertine',
        'Magma Gold Variation 2',
        'Manhattan Grey',
        'Marina Pearl',
        'Martian Soil',
        'Maskaratus',
        'Metallic',
        'Mexican Amber Onyx',
        'Mezzanotte',
        'Michael Angelo Variation 1',
        'Michael Angelo Variation 2',
        'Michael Angelo Variation 3',
        'Michael Angelo Variation 4',
        'Michael Angelo Variation 5',
        'Michael Angelo Variation 6',
        'Michael Angelo Variation 7',
        'Michael Angelo Variation 8',
        'Michael Angelo Variation 9',
        'Michael Angelo Variation10',
        'Michael Angelo Variation11',
        'Michael Angelo Variation12',
        'Michael Angelo Variation13',
        'Michealangelo',
        'Milano',
        'Minorca White',
        'Mirage',
        'Mistike',
        'Mistral',
        'Mont Blanc',
        'Monte Bianco',
        'Monte Bianco Variation 2',
        'Monte Carlo',
        'Montmartre',
        'Moon Cream - Select',
        'Multi Color Travertine',
        'Nacarado',
        'Navagio',
        'New Bronze Amani',
        'New Perlato Royal',
        'New Tobacco Brown',
        'Noche Travertine',
        'Noir St. laurent',
        'Noisette Fleury',
        'Nova Roma',
        'Novelle Cream',
        'Nuvolato Azzuro',
        'Ocean Grey',
        'Olive Fossil',
        'Opal Marine',
        'Opera D\'Arte',
        'Oriental Brown',
        'Panama Gold',
        'Paradise Beige',
        'Patagonia',
        'Pentalico',
        'Perlato Royal',
        'Perlato Sicilia',
        'Persian Blue Onyx',
        'Persian Blue Onyx',
        'Piazzo Navona',
        'Picasso Grey',
        'Pink Crystal Onyx',
        'Pink Onyx',
        'Pink Quartzite',
        'Porto Cervo',
        'Portofino',
        'Portugese Limestone',
        'Quartzite Ice Flake',
        'Red Travertine',
        'Regal Beige',
        'Renoir',
        'Revolution',
        'Riviera Delmare Onyx',
        'RM Bronze',
        'Roma',
        'Roma Imperiale',
        'Roman Grey - Dark Selection',
        'Roman Versailles',
        'Rossa Gold Travertine',
        'Rosso Alicante',
        'Rosso Espanol',
        'Rosso Lavante',
        'Rosso Orobico',
        'Rosso Statuario',
        'Royal Antic Beige',
        'Royal Cream',
        'Royal Cream Variation 2',
        'Royal Vendome',
        'San Diego Red',
        'San Lorenzo',
        'San Luiz',
        'Santa Cecilia',
        'Santorini Variation 1',
        'Santorini Variation 2',
        'Sarizzo',
        'Sarran Colin  ( Opera Fantastico )',
        'Saturnia',
        'Siena Broccato',
        'Silver Cloud',
        'Silver Dove',
        'Silver Emperador',
        'Silver Fantastic Beige',
        'Silver Ice',
        'Silver Martini Tra Onyx',
        'Silver Paradiso Travertine',
        'Silver Serpeggiante',
        'Silver Travertine',
        'Sky Gold',
        'Smoky Brown',
        'Sofia Beige',
        'Spanish Beige',
        'Spectrolite',
        'Spectrus Gold',
        'Spring Grey',
        'St. Topez',
        'Statuario Variation 1',
        'Statuario Variation 2',
        'Summer Light Silver',
        'Super White',
        'Taj Mahal Variation 1',
        'Taj Mahal Variation 2',
        'Tamarino',
        'Tanzania',
        'Tartaruga',
        'Tartaruga',
        'Tempest',
        'Temptation Blue',
        'Terracota',
        'Terracotta',
        'Thale Blue',
        'Titanium Grey',
        'Titanium Travertine',
        'Tobacco Brown',
        'Tobacco Brown - Cross Cut',
        'Topazio Imperial',
        'Torroncino',
        'Tra Onyx Giallo Persiano',
        'Tremendal Bordeave',
        'Triple Fusion',
        'Valconic Ash',
        'Valentine',
        'Vanilla Onyx',
        'Vatican Tra Onyx',
        'Vega Blue',
        'Venetian Brown',
        'Venetino White',
        'Verde Lapponia',
        'Versilia Grey',
        'Vibranium',
        'Victoria Beige',
        'Vitoria Regia',
        'Vogue Grey',
        'Volakas White',
        'Vulcano',
        'Vulcano Crystal',
        'Vulcano Crystal Variation 2',
        'Walnut Travertine',
        'White Cloud',
        'White Equator',
        'White Gold',
        'White Onyx',
        'White Onyx Extra',
        'White Persian Onyx',
        'White Tiger',
        'White Travertine',
        'Xposed Concrete',
        'Yellow Travertine',
        'Zion',
        ]
        return marble_name;
    },
    getMarbleLink: function() {
        var marble_link = ['acupullo-brown.jpg',
        'Alaska-Grey-1.jpg',
        'Alaska-Grey-light-premium.jpg',
        'Alpin.jpg',
        'Amarone-1.jpg',
        'Amazon-1900.jpg',
        'American-Grey-1.jpg',
        'Antigua-Brown.jpg',
        'Antique-Beige-1.jpg',
        'Aragonite-1.jpg',
        'Armani-Cream-2-1.jpg',
        'Armani-Grey-1.jpg',
        'Ash-Grey-1.jpg',
        'Astrus-1.jpg',
        'Astrus-Grey-Var-2.jpg',
        'Astrus-Grey-Variation-1-1.jpg',
        'Aura-1900.jpg',
        'Avocatus.jpg',
        'Avorio-1.jpg',
        'Azul-Macaubas-1900.jpg',
        'Azul-Macaubas-2-1900.jpg',
        'Beige-Serpegiante.jpg',
        'Beige-Travertine-2.jpg',
        'Midnight-Black-1.jpg',
        'Bellatrix-1.jpg',
        'Belvedere-1.jpg',
        'Bethany-Blue-1900.jpg',
        'Beverely-Blue-1900.jpg',
        'Bianco-Fusion-2-1.jpg',
        'Bianco-Oro-1.jpg',
        'Bianco-Oro-Extra-Classico-1.jpg',
        'Bianco-Romano-Classico-1.jpg',
        'Biancone-1.jpg',
        'Black-Gold-Daytona.jpg',
        'Black-fusion-1.jpg',
        'Black-Horse.jpg',
        'Black-Ice-Pearl-1.jpg',
        'Black-Marinace.jpg',
        'Black-Shadow.jpg',
        'Diaspro-1.jpg',
        'Black-Valley.jpg',
        'Blanc-Luminix-1900.jpg',
        '285-BLUE-BAHIA.jpg',
        'Blue-Flamingo-1.jpg',
        'Blue-Fusion-1900.jpg',
        'Blue-Onyx-1.jpg',
        'Blue-Onyx-Marble-1380.jpg',
        'blue-onyx-marble-Slab-2-1380.jpg',
        'Blue-St.-Topez-1.jpg',
        'Borgini-Gold.jpg',
        'Botanic-Green-2.jpg',
        'Bottocino-Classico-1.jpg',
        'Botticino-Crema.jpg',
        'Botticino-Gold-Onyx-1.jpg',
        'Brasil-Bronzetto-1.jpg',
        'Breche-Bluette-1.jpg',
        'Brescia-Aurora-1.jpg',
        'Brescia-Blue-1.jpg',
        'Brescia-Estrella-1.jpg',
        'Brescia-Medicea-1.jpg',
        'Brescia-Onciata-1.jpg',
        'Bronze-Amani-1.jpg',
        'Bronze-Star-1.jpg',
        'Brown-antico-1.jpg',
        'Brown-Earth-1.jpg',
        'Brown-Malibu-1.jpg',
        'Elegant-Brown.jpg',
        'Bulgari-Grey.jpg',
        'Cafe-Amro-1.jpg',
        'Calacata-Quartz-1.jpg',
        'Calacata.jpg',
        'California-Golden-grey-Marble.jpg',
        'Carpe-Diem-1.jpg',
        'Cheyene-2.jpg',
        'Circuit-Grey-1900.jpg',
        'Classic-Beige-1.jpg',
        'Classic-Wave-1.jpg',
        'FRENCH-CREAM-1.jpg',
        'Novelle-Cream-Variation-1-1.jpg',
        'Cleopatra-1.jpg',
        'Colonial-Blue.jpg',
        'Copa-Cabana-1.jpg',
        'Coral-Reef-1.jpg',
        'Cosmopolitian-1900.jpg',
        'Crema-Atlantica-1.jpg',
        'Crema-Delicatus-Onyx.jpg',
        'Crema-Lux-1.jpg',
        'Crema-Valencia-1.jpg',
        'Crema-Versaillies-onyx-1.jpg',
        'Cristallo-1900.jpg',
        'Cristallo-Striato-Onyx-1.jpg',
        'Dark-Emperador-1.jpg',
        'Bianco-Venato-1.jpg',
        'Delux-1900.jpg',
        'Desert-Eagle-1900.jpg',
        'Devci-Grey.jpg',
        'Diana-Classico-1.jpg',
        'Dijon-Blue.jpg',
        'Duetto-1.jpg',
        'Emerald-Quartzite-1.jpg',
        'Equilibrium-1.jpg',
        'Esparada-1.jpg',
        'Exuberant-Brown-1900.jpg',
        'Fascination-1900.jpg',
        'Fascination-Crystal-1900.jpg',
        'Fenix-Gold.jpg',
        'Fior-De-Pesco-1.jpg',
        'Fiora-Grey-1.jpg',
        'Flamingo-1.jpg',
        'Fontaine-2.jpg',
        'Foresta-1.jpg',
        'Fossena-1.jpg',
        'Fossil-Element.jpg',
        'French-Chiffon-1.jpg',
        'Fusion-1.jpg',
        'Fusion-Mint-1.jpg',
        'Gabana-1.jpg',
        'Gaya-1900.jpg',
        'Giallo-Siena-1.jpg',
        'Glacial-Perla.jpg',
        'Golden-Blue-1.jpg',
        'Golden-Caramel-1.jpg',
        'Golden-Dream-Recovered.jpg-1900x962.jpg',
        'Golden-Emperador-1.jpg',
        'Golden-Fenix.jpg',
        'Golden-Flame.jpg',
        'Golden-Fusion-1900.jpg',
        'Golden-Portoro-1.jpg',
        'Golden-Spider-1.jpg',
        'Greek-Chainti-1.jpg',
        'Greek-Grey-1380x699.jpg',
        'Greek-Rosa-Travertine-marbel.jpg',
        'Grey-Corte.jpg',
        'Grey-Dragon.jpg',
        'Grey-Dusk-1.jpg',
        '4938130r9DTBNW.jpg',
        'Grey-Frappuccino.jpg',
        'Grey-Rio-1.jpg',
        'Grey-Riviera.jpg',
        'Grey-Santorini-1.jpg',
        'Grey-Silver-Travertine-1.jpg',
        'Grey-Sonata-1.jpg',
        'Grey-Sparkle-1.jpg',
        '131-GREY-WILLIAM.jpg',
        'Grey-William-1.jpg',
        'Grigio-Amani.jpg',
        'Grigio-Arizona-1.jpg',
        'Grigio-Carnico-1.jpg',
        'Grigio-Carpazi.jpg',
        'Grigio-Celina-1.jpg',
        'Grigio-Cielo-1900.jpg',
        'Grigio-Coralito.jpg',
        'Grigio-DIstria-1.jpg',
        'Grigio-Esmeralda.jpg',
        'Grigio-Espanol-1.jpg',
        'Grigio-Orobico-1.jpg',
        'Hollywood-Red-2.jpg',
        'Honey-Lime-Onyx-1380.jpg',
        'Horizon.jpg',
        'Ice-Berg-Blue.jpg',
        'Ice-Berg-Onyx.jpg',
        'Ice-Blue.jpg',
        'Ice-Onyx-variation-2-2.jpg',
        'Ijen-Blue-1900.jpg',
        'Ijen-Blue-1900-1.jpg',
        'Illusion-1900.jpg',
        'Illusion-Brown-1380.jpg',
        'Infinity-Gold.jpg',
        'Invictus-1.jpg',
        'Italia-Blue-Onyx-1.jpg',
        'Italia-Grey-1.jpg',
        'Jade-Green-Onyx-1.jpg',
        'Keylin-Onyx.jpg',
        'Kozmus-1.jpg',
        'La-Fabula-1.jpg',
        'lemurian-1.jpg',
        'Light-Emperador-Golden-1.jpg',
        'Landon-Grey-1900.jpg',
        'London-Grey-2-1900.jpg',
        'Luise-Cielo.jpg',
        'Lumix-1.jpg',
        'Luxuria-1.jpg',
        'Magma-Gold-1.jpg',
        'Magma-Gold-Travertine-1.jpg',
        'Magma-Gold-1900.jpg',
        'Manhattan-Grey.jpg',
        '494031iOHeoBv8.jpg',
        'Martian-Soil-1900.jpg',
        'Maskaratus-1.jpg',
        'Metallic-1.jpg',
        'Mexican-Amber-Onyx-1.jpg',
        'Mezzanote.jpg',
        'Micheal-Angelo-7-1.jpg',
        'Micheal-Angelo-1-1.jpg',
        'Micheal-Angelo-4-1.jpg',
        'Micheal-Angelo-5-1.jpg',
        'Micheal-Angelo-3-2.jpg',
        'Micheal-Angelo-6-1.jpg',
        '259-MICHAEL-ANGELO.jpg',
        '262-MICHAEL-ANGELO.jpg',
        'Portugeaus-Rossa-Porina-1.jpg',
        'Micheal-Angelo-10.jpg',
        'Michael-Angelo-Variation11-1380.jpg',
        'Michael-Angelo-Variation12-1380.jpg',
        'Michael-Angelo-Variation13-1380.jpg',
        'Bianco-Waves-1.jpg',
        'Milano-1900.jpg',
        'Minorca-White.jpg',
        'Mirage-1.jpg',
        'Mistike-1900.jpg',
        'Mistral.jpg',
        'Mont-Blanc.jpg',
        'Monte-Bianco-1.jpg',
        'Monte-Bianco-1900.jpg',
        'Monte-carlo-1.jpg',
        'Montmartre-1.jpg',
        'moon-cream-select-2.jpg',
        'Multi-Color-Travertine-1.jpg',
        'Nacarado-1.jpg',
        'Navagio.jpg',
        'New-Bronze-Amani-2.jpg',
        'New-Perlato-Royal-1.jpg',
        'New-Tobacco-Brown-1.jpg',
        'Noche-Travertine-1.jpg',
        'Noir-St.-laurent-1.jpg',
        'Noisette-Fleury-1.jpg',
        'Nova-Roma-1.jpg',
        'Novelle-Cream-1.jpg',
        'Nuvolato-Azzuro-1900.jpg',
        'Ocean-Grey-1.jpg',
        'Olive-Fossil-1.jpg',
        'opal-marine-1.jpg',
        'Opera-DArte-1.jpg',
        'Oriental-Brown-1.jpg',
        'Panama-Gold-1.jpg',
        'Paradise-Beige.jpg',
        'Patagonia-1.jpg',
        'Pentalico.jpg',
        'parlato-royal.jpg',
        'Perlato-Sicilia-1.jpg',
        '48231CMIFHXGw.jpg',
        'Persian-Blue-Onyx.jpg',
        'Piazzo-Navona-1.jpg',
        'Grey-piccaso.jpg',
        '196-PINK-CRYSTAL-ONYX.jpg',
        'Pink-Onyx-2.jpg',
        'Pink-Quartzite.jpg',
        'Porto-Cervo-1.jpg',
        'Portofino-1.jpg',
        'Portugese-Limestone-1.jpg',
        'Quartzite-Ice-Flake-1.jpg',
        'Red-Travertine-1.jpg',
        'Regal-Beige-1.jpg',
        'Renoir-Variation-2-1.jpg',
        'Revolution-1900.jpg',
        'Riviera-Delmare-Onyx-1.jpg',
        'RM-BRONZE-1380.jpg',
        'Roma-1900-1.jpg',
        'Roma-Imperiale-1900.jpg',
        'Roman-Grey-Dark-Selection.jpg',
        'Roman-Versailles-3.jpg',
        '231-ROSSA-GOLD-TRAVERTINE.jpg',
        'Rosso-Alicante-1.jpg',
        'Rosso-Espanol-2.jpg',
        'Rosso-lavante-1.jpg',
        'Rosso-Orobico-1.jpg',
        'Rosso-Statuario-1.jpg',
        'Royal-Antic-Beige-1380x699.jpg',
        'Royal-Cream-1.jpg',
        'Royal-Cream-Variation-2.jpg',
        'Royal-Vendome-1.jpg',
        'Sandiego-Red-1.jpg',
        'San-Lorenzo-2.jpg',
        'San-Luiz-1.jpg',
        'Santa-Cecilia-1.jpg',
        'Santorini.jpg-1900.jpg',
        'Santorini-1-1900.jpg',
        'Sarizzo-1.jpg',
        'Sarran-Colin-Opera-Fantastico.jpg',
        'Saturnia-1900.jpg',
        'Siena-Broccato-3.jpg',
        'Silver-Cloud.jpg',
        'Silver-Dove.jpg',
        'Silver-Emperador-1.jpg',
        'BULGARIA-BEIGE.jpg-1900.jpg',
        'silver-Ice-1.jpg',
        'Silver-Martni-Tra-Onyx-1.jpg',
        '233-SILVER-PARADISO-TRAVERTINE.jpg',
        '166-SILVER-SERPEGGIANTE.jpg',
        'Silver-Travertine-1.jpg',
        'Sky-Gold.jpg',
        'Smoky-Brown-1.jpg',
        'Sofia-Beige-1.jpg',
        'Defonate-1.jpg',
        'Spectrolite-1.jpg',
        'Spectrus-Gold-1.jpg',
        'Spring-Grey.jpg',
        'St.-Topez-1.jpg',
        'Statuario-Variation-1.jpg',
        'Statuario-2.jpg',
        'Summer-Light-Silver-2.jpg',
        'Super-White.jpg',
        'Taj-Mahal-1.jpg',
        'Taj-Mahal-1-1900.jpg',
        'Tamarino.jpg',
        'Tanzania-1900.jpg',
        'Tartaruga-1.jpg',
        'Tartaruga-1900.jpg',
        'Temptest.jpg',
        'Temptation-Blue-Slab.jpg',
        'Terracota.jpg',
        'Terracotta-1.jpg',
        'Thale-Blue-1900.jpg',
        'Titanium-Grey-1.jpg',
        'Titanium-Travertine-3.jpg',
        'Tobacco-Brown-1.jpg',
        'Tobacco-Brown-Cross-Cut.jpg',
        'Topazio-Imperial-1900.jpg',
        'Torroncino-1.jpg',
        'Tra-Onyx-Gialo-Periano-1.jpg',
        'Tremendal-Bordeave.jpg',
        'Triple-Fusion-1900.jpg',
        'Valconic-Ash.jpg',
        'Valentine-1.jpg',
        '201-VANILLA-ONYX.jpg',
        'Vatican-Tra-Onyx-1.jpg',
        'Vega-Blue-1.jpg',
        'Venetian-Brown-1.jpg',
        'Venetino-White-1.jpg',
        'Verde-Lapponia-1.jpg',
        'Versilia-grey-1380.jpg',
        'Vibranium-1900.jpg',
        'victoria-beige-compressed.jpg',
        'Vitoria-Regia.jpg',
        'Vogue-Grey.jpg',
        'Volakas-White-1.jpg',
        'Vulcano-1.jpg',
        'Vulcano-Crystal-1900.jpg',
        'Vulcano-Crystal-2-1900.jpg',
        'Wallnut-Travertine-1.jpg',
        'White-Cloud-1900.jpg',
        'White-Equator-1.jpg',
        'White-Gold-1.jpg',
        'White-Onyx-1.jpg',
        'White-Onyx-Extra-1.jpg',
        'White-Original-Persian-Onyx-1.jpg',
        'White-Tiger-1900.jpg',
        'White-Travertine-1.jpg',
        'Xposed-Concrete.jpg',
        'Yellow-Travertine-1.jpg',
        'Zion-1900.jpg',
        ]
        return marble_link
    }
  };